url: http://qwinix.github.io/gophercon.ae
title: Default Page

github_project_name: http://qwinix.github.io/gophercon.ae

google_analytics_tracking_id: UA-51493925-1
google_analytics_tracking_domain: auto

exclude: ["Gemfile", "Gemfile.lock", "bin"]

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown

disqus_shortname: defaultjekyll

twitter_username: defaultjekyll

encoding: UTF-8
