# Site settings
title: "Gophercon Dubai 2016"
email: "ecosystem@squarecircletech.com"
url: "https://gophercon.ae"
description: "The Go language is taking the world by storm! At the conference you will get to meet, interact and learn from Go experts coming from across the globe."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'
  brand: '#ffd73d'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/gopherconae
  - title: facebook
    url: https://www.facebook.com/GopherConAE/

register_url: "https://www.eventbrite.com/e/gophercon-dubai-2016-tickets-19951951825"
# Build settings
markdown: kramdown
permalink: pretty

font-family: Lato, Roboto, Montserrat,"Helvetica Neue",Helvetica,Arial,sans-serif
