# Site settings
title: "Gophercon Dubai 2016"
email: "ecosystem@squarecircletech.com"
url: "https://gophercon.ae"
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'
  brand: '#ffd73d'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/gopherconae
  - title: facebook
    url: https://www.facebook.com/GopherConAE/

register_url:
# Build settings
markdown: kramdown
permalink: pretty

font-family: Lato, Roboto, Montserrat,"Helvetica Neue",Helvetica,Arial,sans-serif
